// src/themes/themes.js
// 10 fully defined Chronicle themes

export const THEMES = {
  broadsheet: {
    id: 'broadsheet',
    name: 'Broadsheet',
    emoji: '📰',
    description: 'Classic daily newspaper',
    bg: '#f5f0e8',
    surface: '#ede6d4',
    card: '#f9f5ed',
    border: '#c9b99a',
    rule: '#2c1f0e',
    text: '#1a1208',
    textSecondary: '#6b5d4f',
    accent: '#8b1a1a',
    accentText: '#fff',
    headerBg: '#f5f0e8',
    headerText: '#1a1208',
    titleFont: 'serif',
    bodyFont: 'serif',
    cardStyle: 'column',
    dark: false,
  },
  vintage: {
    id: 'vintage',
    name: 'Vintage Gazette',
    emoji: '🗞️',
    description: 'Aged 1920s gazette',
    bg: '#e8dcc8',
    surface: '#ddd0b8',
    card: '#ede0c8',
    border: '#b09070',
    rule: '#5c3d1e',
    text: '#3b2510',
    textSecondary: '#7a5c3a',
    accent: '#c17f24',
    accentText: '#fff',
    headerBg: '#5c3d1e',
    headerText: '#f5e8d0',
    titleFont: 'serif',
    bodyFont: 'serif',
    cardStyle: 'bordered',
    dark: false,
  },
  darkink: {
    id: 'darkink',
    name: 'Dark Ink',
    emoji: '🖤',
    description: 'Night edition, deep black',
    bg: '#0d0d0d',
    surface: '#1a1a1a',
    card: '#161616',
    border: '#2a2a2a',
    rule: '#444',
    text: '#e8e0d0',
    textSecondary: '#888',
    accent: '#c9a84c',
    accentText: '#0d0d0d',
    headerBg: '#0d0d0d',
    headerText: '#e8e0d0',
    titleFont: 'serif',
    bodyFont: 'serif',
    cardStyle: 'column',
    dark: true,
  },
  minimal: {
    id: 'minimal',
    name: 'Modern Minimal',
    emoji: '◻️',
    description: 'Clean, airy, typographic',
    bg: '#ffffff',
    surface: '#f8f8f8',
    card: '#ffffff',
    border: '#e0e0e0',
    rule: '#111',
    text: '#111',
    textSecondary: '#888',
    accent: '#111',
    accentText: '#fff',
    headerBg: '#fff',
    headerText: '#111',
    titleFont: 'sans-serif',
    bodyFont: 'sans-serif',
    cardStyle: 'minimal',
    dark: false,
  },
  tabloid: {
    id: 'tabloid',
    name: 'Tabloid',
    emoji: '📣',
    description: 'Bold, punchy, loud',
    bg: '#fff9f0',
    surface: '#fff3e0',
    card: '#ffffff',
    border: '#ff6600',
    rule: '#cc0000',
    text: '#1a0000',
    textSecondary: '#cc3300',
    accent: '#cc0000',
    accentText: '#fff',
    headerBg: '#890505',
    headerText: '#ffffff',
    titleFont: 'sans-serif',
    bodyFont: 'sans-serif',
    cardStyle: 'bold',
    dark: false,
  },
  magazine: {
    id: 'magazine',
    name: 'Magazine',
    emoji: '✨',
    description: 'Glossy, modern editorial',
    bg: '#fafafa',
    surface: '#f0f0f0',
    card: '#ffffff',
    border: '#ddd',
    rule: '#222',
    text: '#1a1a2e',
    textSecondary: '#666',
    accent: '#e91e8c',
    accentText: '#fff',
    headerBg: '#1a1a2e',
    headerText: '#ffffff',
    titleFont: 'sans-serif',
    bodyFont: 'sans-serif',
    cardStyle: 'card',
    dark: false,
  },
  academic: {
    id: 'academic',
    name: 'Academic',
    emoji: '📚',
    description: 'Essay, scholarly journal',
    bg: '#f7f5f0',
    surface: '#eeeae0',
    card: '#f7f5f0',
    border: '#c8c0a8',
    rule: '#2c3e50',
    text: '#2c3e50',
    textSecondary: '#7f8c8d',
    accent: '#2980b9',
    accentText: '#fff',
    headerBg: '#2c3e50',
    headerText: '#ecf0f1',
    titleFont: 'serif',
    bodyFont: 'serif',
    cardStyle: 'bordered',
    dark: false,
  },
  typewriter: {
    id: 'typewriter',
    name: 'Typewriter',
    emoji: '⌨️',
    description: 'Retro mechanical type',
    bg: '#f2ede4',
    surface: '#e8e0d0',
    card: '#f5f0e8',
    border: '#b0a090',
    rule: '#3a3028',
    text: '#3a3028',
    textSecondary: '#7a6a5a',
    accent: '#8b6914',
    accentText: '#fff',
    headerBg: '#3a3028',
    headerText: '#f2ede4',
    titleFont: 'monospace',
    bodyFont: 'monospace',
    cardStyle: 'typewriter',
    dark: false,
  },
  neon: {
    id: 'neon',
    name: 'Neon Cyberpunk',
    emoji: '⚡',
    description: 'Dark futuristic neon glow',
    bg: '#050510',
    surface: '#0a0a20',
    card: '#0d0d1f',
    border: '#1a1a3a',
    rule: '#00f5ff',
    text: '#e0e8ff',
    textSecondary: '#7a8aaa',
    accent: '#00f5ff',
    accentText: '#050510',
    headerBg: '#050510',
    headerText: '#00f5ff',
    titleFont: 'monospace',
    bodyFont: 'monospace',
    cardStyle: 'neon',
    dark: true,
  },
  pastel: {
    id: 'pastel',
    name: 'Soft Diary',
    emoji: '🌸',
    description: 'Gentle, warm personal diary',
    bg: '#fef6f0',
    surface: '#fde8e0',
    card: '#fff9f6',
    border: '#f5c6b8',
    rule: '#d4847a',
    text: '#4a2828',
    textSecondary: '#b08888',
    accent: '#d4847a',
    accentText: '#fff',
    headerBg: '#f5c6b8',
    headerText: '#4a2828',
    titleFont: 'serif',
    bodyFont: 'serif',
    cardStyle: 'soft',
    dark: false,
  },
};

export const THEME_LIST = Object.values(THEMES);
export const DEFAULT_THEME = 'broadsheet';
